name: Generate Metrics

on:
  schedule: 
    - cron: "0 0 * * 1"  
  workflow_dispatch:     
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Aftabul-islam
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_lines: yes             
          plugin_languages: yes
          plugin_stars: yes
          plugin_traffic: yes
          plugin_isocalendar: yes
          plugin_habits: yes
          plugin_habits_facts: yes
